// <auto-generated />
using System;
using Arckdan.Mayday.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arckdan.Mayday.Repository.Migrations
{
    [DbContext(typeof(MaydayMySqlContext))]
    partial class MaydayMySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Arckdan.Mayday.Domain.Comunidade.LandingPageModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime?>("Alteracao")
                        .HasColumnType("Datetime")
                        .HasAnnotation("Relational:JsonPropertyName", "dataAlteracao");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("Varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "cidade");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("Varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("Varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "ip");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("Datetime")
                        .HasAnnotation("Relational:JsonPropertyName", "dataInclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "nome");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasAnnotation("Relational:JsonPropertyName", "tokenSeguranca");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("Char")
                        .HasAnnotation("Relational:JsonPropertyName", "uf");

                    b.Property<long?>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "whatsApp");

                    b.HasKey("Id");

                    b.ToTable("tb_mayday_landing_page");
                });
#pragma warning restore 612, 618
        }
    }
}
